#Stage: Import packages

In [1]:
import sys
import os

print (os.getcwd())

/Users/niloy/Library/CloudStorage/OneDrive-Personal/Desktop/My Projects/Mutual Fund Analyzer/emfer_code/notebooks

In [2]:
os.chdir("..")
print (os.getcwd())

/Users/niloy/Library/CloudStorage/OneDrive-Personal/Desktop/My Projects/Mutual Fund Analyzer/emfer_code

#Stage: Import MF NAV history

In [3]:
from src.emfer.data.mf_api import fetch_nav_history
mf_df, mf_name = fetch_nav_history(125497)

/Users/niloy/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [4]:
print (mf_name)
mf_df.head()

SBI Small Cap Fund - Direct Plan - Growth

           date      nav                                  fund_name
3086 2013-11-18  13.0894  SBI Small Cap Fund - Direct Plan - Growth
3085 2013-11-19  13.1068  SBI Small Cap Fund - Direct Plan - Growth
3084 2013-11-20  12.9549  SBI Small Cap Fund - Direct Plan - Growth
3083 2013-11-21  12.7957  SBI Small Cap Fund - Direct Plan - Growth
3082 2013-11-22  12.7775  SBI Small Cap Fund - Direct Plan - Growth

In [5]:
from src.emfer.data.rolling_returns import calculate_rolling_returns, get_nearest_past_index
df_rolling = calculate_rolling_returns(mf_df, n=5)
#df_rolling.head()

In [6]:
df_rolling.head()

,current_date,past_date,cagr_5_years,current_nav,past_nav,fund_name,fund
0,2018-11-19,2013-11-19,32.252336,53.0290,13.1068,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
1,2018-11-20,2013-11-20,32.402064,52.7118,12.9549,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
2,2018-11-21,2013-11-21,32.714131,52.6805,12.7957,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
3,2018-11-22,2013-11-22,32.704609,52.5867,12.7775,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
4,2018-11-26,2013-11-26,32.425943,52.3692,12.8591,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund

In [9]:
from src.emfer.charts.charts import plot_nav
plot_nav(df_rolling)

KeyError: 'date'

In [10]:
from src.emfer.charts.charts import rolling_returns_summary
df_summary = rolling_returns_summary(df_rolling, 5)

In [11]:
df_summary.head()

,fund_name,start_date,end_date,metric,latest_5_year_cagr,mean,std_dev,min,p5,p10,p25,median,p75,p90,p95,max
0,SBI Small Cap Fund - Direct Plan - Growth,2013-11-19,2026-05-26,5Y CAGR,14.82,21.81,5.95,7.4,11.62,14.49,17.19,21.91,25.95,30.31,31.34,34.51

In [12]:
from src.emfer.genAI.fund_store import create_fund_store
fund_store = create_fund_store(df_rolling, df_summary)

In [13]:
fund_store.keys()

dict_keys(['SBI Small Cap Fund - Direct Plan - Growth'])

In [14]:
fund_store['SBI Small Cap Fund - Direct Plan - Growth'].keys()

dict_keys(['rolling_nav_cagr', 'summary'])

In [15]:
fund_store['SBI Small Cap Fund - Direct Plan - Growth']['rolling_nav_cagr'].head()

,current_date,past_date,cagr_5_years,current_nav,past_nav,fund_name,fund
0,2018-11-19,2013-11-19,32.252336,53.0290,13.1068,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
1,2018-11-20,2013-11-20,32.402064,52.7118,12.9549,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
2,2018-11-21,2013-11-21,32.714131,52.6805,12.7957,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
3,2018-11-22,2013-11-22,32.704609,52.5867,12.7775,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund
4,2018-11-26,2013-11-26,32.425943,52.3692,12.8591,SBI Small Cap Fund - Direct Plan - Growth,SBI Small Cap Fund

In [16]:
from src.emfer.genAI.fund_store import build_rag_context
rag_context = build_rag_context(fund_store)

In [17]:
print (rag_context)

                            Fund Name: SBI Small Cap Fund - Direct Plan - Growth

                            Summary:
                                                            fund_name start_date   end_date  metric  latest_5_year_cagr  mean  std_dev  min    p5   p10   p25  median   p75   p90   p95   max
SBI Small Cap Fund - Direct Plan - Growth 2013-11-19 2026-05-26 5Y CAGR               14.82 21.81     5.95  7.4 11.62 14.49 17.19   21.91 25.95 30.31 31.34 34.51

                            Rolling NAV and CAGR Analysis:
                            current_date  past_date  cagr_5_years  current_nav  past_nav                                 fund_name               fund
  2018-11-19 2013-11-19     32.252336      53.0290   13.1068 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-20 2013-11-20     32.402064      52.7118   12.9549 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-21 2013-11-21     32.714131      52.6805   12.7957 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-22 2013-11-22     32.704609      52.5867   12.7775 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-26 2013-11-26     32.425943      52.3692   12.8591 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-27 2013-11-27     32.472392      52.3787   12.8389 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-28 2013-11-28     32.426690      52.4448   12.8773 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-29 2013-11-29     32.302101      52.4969   12.9509 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-30 2013-11-29     32.425511      52.7422   12.9509 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-03 2013-12-03     32.331861      52.7747   13.0048 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-04 2013-12-04     32.468322      52.9458   12.9799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-05 2013-12-05     32.152224      52.5267   13.0319 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-06 2013-12-06     31.813689      51.9051   13.0439 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-07 2013-12-06     31.865809      52.0078   13.0439 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-10 2013-12-10     31.528425      51.3010   13.0325 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-11 2013-12-11     31.768631      51.6933   13.0129 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-12 2013-12-12     32.285911      52.6722   13.0021 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-13 2013-12-13     32.500345      53.0474   12.9891 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-14 2013-12-13     32.521519      53.0898   12.9891 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-17 2013-12-17     32.689607      53.2949   12.9569 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-18 2013-12-18     32.563518      53.4937   13.0672 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-19 2013-12-19     32.696557      54.0589   13.1392 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-20 2013-12-20     32.668257      54.1591   13.1776 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-21 2013-12-20     32.345053      53.5026   13.1776 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-24 2013-12-24     31.816911      52.8045   13.2683 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-26 2013-12-26     31.404331      52.8170   13.4811 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-27 2013-12-27     31.471851      53.0365   13.5024 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-28 2013-12-27     31.709608      53.5178   13.5024 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-31 2013-12-31     31.425510      53.8265   13.7277 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-01 2014-01-01     31.394379      53.8180   13.7418 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-02 2014-01-02     31.318157      53.7148   13.7553 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-03 2014-01-03     31.037453      53.5067   13.8494 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-04 2014-01-03     30.950250      53.3289   13.8494 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-07 2014-01-07     30.858543      53.4187   13.9214 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-08 2014-01-08     30.614287      53.2516   14.0081 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-09 2014-01-09     30.907612      53.2998   13.8644 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-10 2014-01-10     30.974149      53.2423   13.8143 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-11 2014-01-10     30.946536      53.1862   13.8143 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-14 2014-01-14     30.910938      53.1547   13.8249 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-15 2014-01-15     30.602200      53.2756   14.0209 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-16 2014-01-16     30.598938      53.2055   14.0042 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-17 2014-01-17     30.994603      53.1674   13.7841 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-18 2014-01-17     30.947066      53.0710   13.7841 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-21 2014-01-21     30.687043      52.8580   13.8659 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-22 2014-01-22     30.406261      52.5351   13.9302 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-23 2014-01-23     30.231123      52.2713   13.9537 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-24 2014-01-24     30.399757      52.2905   13.8688 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-25 2014-01-24     30.154297      51.8002   13.8688 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-28 2014-01-28     30.364347      51.0862   13.5678 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-29 2014-01-29     30.483378      51.0547   13.4977 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-30 2014-01-30     30.519390      51.0055   13.4661 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-31 2014-01-31     30.425893      51.3507   13.6059 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-01 2014-01-31     30.398705      51.2972   13.6059 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-04 2014-02-04     30.524039      51.0358   13.4717 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-05 2014-02-05     30.221844      50.7151   13.5431 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-06 2014-02-06     30.044851      50.5395   13.5883 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-07 2014-02-07     30.289495      50.8924   13.5552 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-08 2014-02-07     30.115353      50.5532   13.5552 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-11 2014-02-11     29.630285      50.1417   13.6983 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-12 2014-02-12     29.570565      49.9865   13.6874 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-13 2014-02-13     29.551743      49.9159   13.6780 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-14 2014-02-14     29.766371      50.0246   13.5948 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-15 2014-02-14     29.668532      49.8363   13.5948 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-18 2014-02-18     29.447535      49.7231   13.6801 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-19 2014-02-19     29.463357      50.1932   13.8010 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-20 2014-02-20     29.459147      50.5134   13.8913 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-21 2014-02-21     29.379454      50.8863   14.0370 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-22 2014-02-21     29.496250      51.1164   14.0370 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-25 2014-02-25     29.089040      51.1544   14.2704 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-26 2014-02-26     29.156488      50.9392   14.1733 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-27 2014-02-26     29.019433      50.6695   14.1733 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-28 2014-02-28     29.004335      50.7717   14.2102 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-01 2014-02-28     29.343078      51.4418   14.2102 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-05 2014-03-05     29.366469      52.7007   14.5448 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-06 2014-03-06     29.413769      53.2436   14.6678 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-07 2014-03-07     29.886822      53.7052   14.5275 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-08 2014-03-07     30.000246      53.9401   14.5275 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-11 2014-03-11     30.174113      54.7406   14.6449 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-12 2014-03-12     30.299442      55.2773   14.7175 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-13 2014-03-13     30.270605      55.1959   14.7121 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-14 2014-03-14     30.291951      55.0181   14.6527 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-15 2014-03-14     30.203831      54.8323   14.6527 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-18 2014-03-18     29.952030      54.8356   14.7961 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-19 2014-03-19     30.237085      55.1238   14.7118 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-20 2014-03-20     29.903187      54.7637   14.8045 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-22 2014-03-21     29.614620      54.6498   14.9389 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-25 2014-03-25     29.182381      54.0256   15.0170 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-26 2014-03-26     29.363681      54.4065   15.0172 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-27 2014-03-27     29.391181      54.4600   15.0160 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-28 2014-03-28     29.268796      54.7581   15.1698 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-29 2014-03-28     29.693243      55.6630   15.1698 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-01 2014-04-01     29.670103      56.1772   15.3236 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-02 2014-04-02     29.248894      56.0011   15.5261 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-03 2014-04-03     29.131885      55.6601   15.5016 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-04 2014-04-04     28.870029      55.6447   15.6554 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-05 2014-04-04     29.042982      56.0191   15.6554 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-08 2014-04-07     28.867715      55.8828   15.7238 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-09 2014-04-09     28.686387      55.6612   15.7721 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-10 2014-04-10     28.657924      55.6388   15.7832 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-11 2014-04-11     28.573653      55.7987   15.8805 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-12 2014-04-11     28.630701      55.9226   15.8805 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-15 2014-04-15     28.609896      56.1536   15.9590 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-16 2014-04-16     28.799811      56.1267   15.8341 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-18 2014-04-17     28.397498      55.7232   15.9681 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-22 2014-04-22     27.681628      54.9458   16.1917 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-23 2014-04-23     27.662476      55.0555   16.2362 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-24 2014-04-23     27.762861      55.2723   16.2362 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-25 2014-04-25     27.747667      55.3592   16.2714 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-26 2014-04-25     27.728970      55.3187   16.2714 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-30 2014-04-30     27.741700      55.0830   16.1940 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-02 2014-05-02     27.728912      55.0024   16.1784 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-03 2014-05-02     27.679922      54.8970   16.1784 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-06 2014-05-06     27.455486      54.4976   16.2026 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-07 2014-05-07     27.382023      54.3424   16.2031 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-08 2014-05-08     27.064984      53.8583   16.2601 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-09 2014-05-09     26.984180      53.7084   16.2665 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-10 2014-05-09     26.983045      53.7060   16.2665 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-13 2014-05-13     26.490342      52.8389   16.3180 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-14 2014-05-14     26.508798      53.1004   16.3868 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-15 2014-05-15     26.649910      53.0303   16.2742 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-16 2014-05-16     26.508778      52.9338   16.3354 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-17 2014-05-16     26.575244      53.0730   16.3354 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-20 2014-05-20     26.119693      54.4867   17.0756 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-21 2014-05-21     25.514670      54.0838   17.3618 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-22 2014-05-22     25.130884      54.0958   17.6336 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-23 2014-05-23     25.156970      53.9873   17.5799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-24 2014-05-23     25.620653      54.9948   17.5799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-27 2014-05-27     26.257268      55.9036   17.4244 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-28 2014-05-28     26.145552      56.5415   17.7014 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-29 2014-05-29     26.149317      56.3573   17.6411 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-30 2014-05-30     26.132494      56.1882   17.5999 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-31 2014-05-30     26.263410      56.4804   17.5999 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-03 2014-06-03     26.196709      56.7417   17.7281 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-04 2014-06-04     25.740933      56.7067   18.0406 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-06 2014-06-06     24.799295      56.1253   18.5395 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-07 2014-06-06     24.785372      56.0940   18.5395 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-10 2014-06-10     24.069639      55.7431   18.9611 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-11 2014-06-11     24.313483      55.6770   18.7536 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-12 2014-06-12     24.080750      55.6663   18.9265 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-13 2014-06-13     24.169648      55.3583   18.7545 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-14 2014-06-13     24.110466      55.2265   18.7545 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-17 2014-06-17     23.527043      54.6510   19.0015 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-18 2014-06-18     23.117053      54.3588   19.2167 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-19 2014-06-19     23.077434      54.0946   19.1541 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-20 2014-06-20     23.218343      54.4507   19.1702 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-21 2014-06-20     23.232777      54.4826   19.1702 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-24 2014-06-24     23.062772      54.1894   19.1991 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-25 2014-06-25     23.065349      54.4957   19.3056 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-26 2014-06-26     23.006280      54.9657   19.5189 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-27 2014-06-27     22.876585      55.0970   19.6690 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-28 2014-06-27     22.933180      55.2240   19.6690 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-01 2014-07-01     22.286291      55.3031   20.2237 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-02 2014-07-02     22.142338      55.4560   20.3994 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-03 2014-07-03     21.939668      55.3738   20.5390 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-04 2014-07-04     21.687512      55.4699   20.7887 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-05 2014-07-04     21.417006      54.8561   20.7887 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-08 2014-07-08     21.506008      54.1644   20.4515 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-09 2014-07-09     21.822984      54.0836   20.1567 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund

In [18]:
from src.emfer.genAI.prompts import system_instruction
sys_instruction = system_instruction(rag_context)

In [19]:
print (sys_instruction)

  You are Scout, an AI assistant for mutual fund analysis.

  Your role is to interpret mutual fund performance data in a clear, concise, intuitive, and investor-friendly way.

  Mutual Fund Summary Data:

                            Fund Name: SBI Small Cap Fund - Direct Plan - Growth

                            Summary:
                                                            fund_name start_date   end_date  metric  latest_5_year_cagr  mean  std_dev  min    p5   p10   p25  median   p75   p90   p95   max
SBI Small Cap Fund - Direct Plan - Growth 2013-11-19 2026-05-26 5Y CAGR               14.82 21.81     5.95  7.4 11.62 14.49 17.19   21.91 25.95 30.31 31.34 34.51

                            Rolling NAV and CAGR Analysis:
                            current_date  past_date  cagr_5_years  current_nav  past_nav                                 fund_name               fund
  2018-11-19 2013-11-19     32.252336      53.0290   13.1068 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-20 2013-11-20     32.402064      52.7118   12.9549 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-21 2013-11-21     32.714131      52.6805   12.7957 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-22 2013-11-22     32.704609      52.5867   12.7775 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-26 2013-11-26     32.425943      52.3692   12.8591 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-27 2013-11-27     32.472392      52.3787   12.8389 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-28 2013-11-28     32.426690      52.4448   12.8773 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-29 2013-11-29     32.302101      52.4969   12.9509 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-11-30 2013-11-29     32.425511      52.7422   12.9509 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-03 2013-12-03     32.331861      52.7747   13.0048 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-04 2013-12-04     32.468322      52.9458   12.9799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-05 2013-12-05     32.152224      52.5267   13.0319 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-06 2013-12-06     31.813689      51.9051   13.0439 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-07 2013-12-06     31.865809      52.0078   13.0439 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-10 2013-12-10     31.528425      51.3010   13.0325 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-11 2013-12-11     31.768631      51.6933   13.0129 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-12 2013-12-12     32.285911      52.6722   13.0021 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-13 2013-12-13     32.500345      53.0474   12.9891 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-14 2013-12-13     32.521519      53.0898   12.9891 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-17 2013-12-17     32.689607      53.2949   12.9569 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-18 2013-12-18     32.563518      53.4937   13.0672 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-19 2013-12-19     32.696557      54.0589   13.1392 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-20 2013-12-20     32.668257      54.1591   13.1776 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-21 2013-12-20     32.345053      53.5026   13.1776 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-24 2013-12-24     31.816911      52.8045   13.2683 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-26 2013-12-26     31.404331      52.8170   13.4811 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-27 2013-12-27     31.471851      53.0365   13.5024 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-28 2013-12-27     31.709608      53.5178   13.5024 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2018-12-31 2013-12-31     31.425510      53.8265   13.7277 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-01 2014-01-01     31.394379      53.8180   13.7418 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-02 2014-01-02     31.318157      53.7148   13.7553 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-03 2014-01-03     31.037453      53.5067   13.8494 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-04 2014-01-03     30.950250      53.3289   13.8494 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-07 2014-01-07     30.858543      53.4187   13.9214 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-08 2014-01-08     30.614287      53.2516   14.0081 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-09 2014-01-09     30.907612      53.2998   13.8644 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-10 2014-01-10     30.974149      53.2423   13.8143 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-11 2014-01-10     30.946536      53.1862   13.8143 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-14 2014-01-14     30.910938      53.1547   13.8249 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-15 2014-01-15     30.602200      53.2756   14.0209 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-16 2014-01-16     30.598938      53.2055   14.0042 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-17 2014-01-17     30.994603      53.1674   13.7841 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-18 2014-01-17     30.947066      53.0710   13.7841 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-21 2014-01-21     30.687043      52.8580   13.8659 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-22 2014-01-22     30.406261      52.5351   13.9302 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-23 2014-01-23     30.231123      52.2713   13.9537 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-24 2014-01-24     30.399757      52.2905   13.8688 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-25 2014-01-24     30.154297      51.8002   13.8688 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-28 2014-01-28     30.364347      51.0862   13.5678 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-29 2014-01-29     30.483378      51.0547   13.4977 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-30 2014-01-30     30.519390      51.0055   13.4661 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-01-31 2014-01-31     30.425893      51.3507   13.6059 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-01 2014-01-31     30.398705      51.2972   13.6059 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-04 2014-02-04     30.524039      51.0358   13.4717 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-05 2014-02-05     30.221844      50.7151   13.5431 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-06 2014-02-06     30.044851      50.5395   13.5883 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-07 2014-02-07     30.289495      50.8924   13.5552 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-08 2014-02-07     30.115353      50.5532   13.5552 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-11 2014-02-11     29.630285      50.1417   13.6983 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-12 2014-02-12     29.570565      49.9865   13.6874 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-13 2014-02-13     29.551743      49.9159   13.6780 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-14 2014-02-14     29.766371      50.0246   13.5948 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-15 2014-02-14     29.668532      49.8363   13.5948 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-18 2014-02-18     29.447535      49.7231   13.6801 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-19 2014-02-19     29.463357      50.1932   13.8010 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-20 2014-02-20     29.459147      50.5134   13.8913 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-21 2014-02-21     29.379454      50.8863   14.0370 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-22 2014-02-21     29.496250      51.1164   14.0370 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-25 2014-02-25     29.089040      51.1544   14.2704 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-26 2014-02-26     29.156488      50.9392   14.1733 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-27 2014-02-26     29.019433      50.6695   14.1733 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-02-28 2014-02-28     29.004335      50.7717   14.2102 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-01 2014-02-28     29.343078      51.4418   14.2102 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-05 2014-03-05     29.366469      52.7007   14.5448 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-06 2014-03-06     29.413769      53.2436   14.6678 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-07 2014-03-07     29.886822      53.7052   14.5275 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-08 2014-03-07     30.000246      53.9401   14.5275 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-11 2014-03-11     30.174113      54.7406   14.6449 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-12 2014-03-12     30.299442      55.2773   14.7175 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-13 2014-03-13     30.270605      55.1959   14.7121 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-14 2014-03-14     30.291951      55.0181   14.6527 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-15 2014-03-14     30.203831      54.8323   14.6527 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-18 2014-03-18     29.952030      54.8356   14.7961 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-19 2014-03-19     30.237085      55.1238   14.7118 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-20 2014-03-20     29.903187      54.7637   14.8045 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-22 2014-03-21     29.614620      54.6498   14.9389 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-25 2014-03-25     29.182381      54.0256   15.0170 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-26 2014-03-26     29.363681      54.4065   15.0172 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-27 2014-03-27     29.391181      54.4600   15.0160 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-28 2014-03-28     29.268796      54.7581   15.1698 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-03-29 2014-03-28     29.693243      55.6630   15.1698 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-01 2014-04-01     29.670103      56.1772   15.3236 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-02 2014-04-02     29.248894      56.0011   15.5261 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-03 2014-04-03     29.131885      55.6601   15.5016 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-04 2014-04-04     28.870029      55.6447   15.6554 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-05 2014-04-04     29.042982      56.0191   15.6554 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-08 2014-04-07     28.867715      55.8828   15.7238 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-09 2014-04-09     28.686387      55.6612   15.7721 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-10 2014-04-10     28.657924      55.6388   15.7832 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-11 2014-04-11     28.573653      55.7987   15.8805 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-12 2014-04-11     28.630701      55.9226   15.8805 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-15 2014-04-15     28.609896      56.1536   15.9590 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-16 2014-04-16     28.799811      56.1267   15.8341 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-18 2014-04-17     28.397498      55.7232   15.9681 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-22 2014-04-22     27.681628      54.9458   16.1917 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-23 2014-04-23     27.662476      55.0555   16.2362 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-24 2014-04-23     27.762861      55.2723   16.2362 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-25 2014-04-25     27.747667      55.3592   16.2714 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-26 2014-04-25     27.728970      55.3187   16.2714 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-04-30 2014-04-30     27.741700      55.0830   16.1940 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-02 2014-05-02     27.728912      55.0024   16.1784 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-03 2014-05-02     27.679922      54.8970   16.1784 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-06 2014-05-06     27.455486      54.4976   16.2026 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-07 2014-05-07     27.382023      54.3424   16.2031 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-08 2014-05-08     27.064984      53.8583   16.2601 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-09 2014-05-09     26.984180      53.7084   16.2665 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-10 2014-05-09     26.983045      53.7060   16.2665 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-13 2014-05-13     26.490342      52.8389   16.3180 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-14 2014-05-14     26.508798      53.1004   16.3868 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-15 2014-05-15     26.649910      53.0303   16.2742 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-16 2014-05-16     26.508778      52.9338   16.3354 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-17 2014-05-16     26.575244      53.0730   16.3354 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-20 2014-05-20     26.119693      54.4867   17.0756 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-21 2014-05-21     25.514670      54.0838   17.3618 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-22 2014-05-22     25.130884      54.0958   17.6336 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-23 2014-05-23     25.156970      53.9873   17.5799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-24 2014-05-23     25.620653      54.9948   17.5799 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-27 2014-05-27     26.257268      55.9036   17.4244 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-28 2014-05-28     26.145552      56.5415   17.7014 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-29 2014-05-29     26.149317      56.3573   17.6411 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-30 2014-05-30     26.132494      56.1882   17.5999 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-05-31 2014-05-30     26.263410      56.4804   17.5999 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-03 2014-06-03     26.196709      56.7417   17.7281 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-04 2014-06-04     25.740933      56.7067   18.0406 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-06 2014-06-06     24.799295      56.1253   18.5395 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-07 2014-06-06     24.785372      56.0940   18.5395 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-10 2014-06-10     24.069639      55.7431   18.9611 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-11 2014-06-11     24.313483      55.6770   18.7536 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-12 2014-06-12     24.080750      55.6663   18.9265 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-13 2014-06-13     24.169648      55.3583   18.7545 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-14 2014-06-13     24.110466      55.2265   18.7545 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-17 2014-06-17     23.527043      54.6510   19.0015 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-18 2014-06-18     23.117053      54.3588   19.2167 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-19 2014-06-19     23.077434      54.0946   19.1541 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-20 2014-06-20     23.218343      54.4507   19.1702 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-21 2014-06-20     23.232777      54.4826   19.1702 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-24 2014-06-24     23.062772      54.1894   19.1991 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-25 2014-06-25     23.065349      54.4957   19.3056 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-26 2014-06-26     23.006280      54.9657   19.5189 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-27 2014-06-27     22.876585      55.0970   19.6690 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-06-28 2014-06-27     22.933180      55.2240   19.6690 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-01 2014-07-01     22.286291      55.3031   20.2237 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-02 2014-07-02     22.142338      55.4560   20.3994 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-03 2014-07-03     21.939668      55.3738   20.5390 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-04 2014-07-04     21.687512      55.4699   20.7887 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund
  2019-07-05 2014-07-04     21.417006      54.8561   20.7887 SBI Small Cap Fund - Direct Plan - Growth SBI Small Cap Fund

In [22]:
from src.emfer.genAI.scout import ask_scout
model = ask_scout(sys_instruction)

In [23]:
from src.emfer.genAI.scout import scout_answer
answer = scout_answer(model, "Which funds do you have information on?")
print (answer)

I have information on the **SBI Small Cap Fund - Direct Plan - Growth**.